### ISSUE TITLE
How to show fired rule.

### ISSUE THREAD

**Issue by GabrielLCHeng** [nilp0inter/experta#23]
I want to let the user know which rule are fired based on their respond. How do I show the list of rules that are fired?

**Comment by nilp0inter** [comment]
You can use `watch('RULES')` to enable the rules logger. 

Here is an example https://github.com/nilp0inter/experta/blob/develop/docs/examples/maximum.ipynb

If the format doesn't suit your needs I recommend you make a custom decorator for your rules.
