### ISSUE TITLE
Dynamic rule generating

### ISSUE THREAD

**Issue by abdulrashid123** [nilp0inter/experta#6]
Require to generate rules Dynamically how can i do that can you give me example please

**Comment by nilp0inter** [comment]
What do you mind for dynamically?

1. Generate rules while the KnowledgeEngine is running?
2. Dynamically generate rules before the engine is run?

**Comment by abdulrashid123** [comment]
I want generate rule while knowledge engine is running

**Comment by abdulrashid123** [comment]
something like i can fetch from database

**Comment by abdulrashid123** [comment]
I m using this rule engine to provide solution to to error acquired from logs

**Comment by nilp0inter** [comment]
I am sorry but generating rules *while* the engine is already running is not supported with the current implementation.

**Comment by Behery** [comment]
Hello, 
@nilp0inter is this planned or anywhere on the road map? I can try to help, if you point me to where the bottle neck would be.
@abdulrashid123 did you find a way around this?

Cheers!

**Comment by nilp0inter** [comment]
Sorry, but right now I don't have the time to add more features to Experta.

This maybe can be achieved, but it is not an easy task.  If you come up with a solution I will be happy to review it and maybe merge it into the project.

Happy hacking!

**Comment by Behery** [comment]
Thanks for the reply .. I'll give it a shot and make a PR if I succeed.
